sudo: required
services:
  - docker

before_install:
  - docker build -t maozcyber12/docker-react -f Dockerfile.dev .


script:
  - docker run -t maozcyber12/docker-react npm run test -- --coverage

# Deploy to AWS elasticbeanstalk
deploy:
  provider: elasticbeanstalk
  region: "AWS-REGION"
  app: "APP-NAME"
  env: "ENV-NAME"
  bucket_name: "ELASTIC-BUCKET-NAME"
  # bucket_path: PATH.
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY" 





